# Generated by Django 5.0.4 on 2024-04-07 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(blank=True, max_length=300)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('model_year', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=800)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='store_brand', to='stores.brand')),
            ],
        ),
    ]
