# Generated by Django 5.0.4 on 2024-05-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_iteminventory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemInventory',
            new_name='StoreInventory',
        ),
    ]
