# Generated by Django 5.0.4 on 2024-05-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_rename_iteminventory_storeinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
